name: biograph
channels:
  - pytorch
  - pyg
  - nvidia
  - conda-forge
  - defaults
  - dglteam/label/cu118
dependencies:
  - python=3.11
  - cudatoolkit=11.8
  - pyg
  - pytorch>=2.0
  - torchvision
  - torchaudio
  - torchdata
  - dgl
  - lightning=2.*
  - pydantic>=2.0
  - wandb
  - rich
  - hydra-core
  - jupyter
  - einops
  - symengine
  - numpy
  - scipy
  - matplotlib
  - networkx
  - numba
  - polars
  - pyarrow
  - pip
  - pip:
      - ogb
      - rootutils
      - hydra_colorlog
      - codetiming
      - humanfriendly
      - py2neo
      - neo4j
      - arxiv
      - attr
      - beautifulsoup4
      - configparser
      - cython
      - docutils
      - filelock
      - ipython
      - ipywidgets
      - keyring
      - loguru
      - transformers
      - openai
      - pyOpenSSL
      - pytest
      - python-dotenv
      - redis
      - Sphinx
      - thread
      - torch_geometric
      - tqdm
      - urllib3_secure_extra
      - PyYAML
      - z3
      - pyg_lib
      - torch_scatter
      - torch_sparse
      - torch_cluster
      - torch_spline_conv